---
# tasks file for nica
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Downgrade kernel if needed
  include: downgrade-kernel.yml
  when: mlnx_ofed_downgrade_kernel and ansible_distribution == 'CentOS'

- name: Install MLNX OFED
  include_role: name=haggaie.mlnx_ofed

- name: NICA rpm dependencies
  package:
    name:
    - cmake3
    - libuuid-devel
    - python36-pip
    - python36-scapy
    - boost-devel
    - libpcap-devel
  when: ansible_os_family == 'RedHat'

- name: NICA deb dependencies
  package:
    name:
    - cmake
    - uuid-dev
    - python3-pip
    - python3-scapy
    - libboost-all-dev
    - libcap-dev
    state: latest
  when: ansible_os_family == 'Debian'

- name: NICA pip dependencies
  pip:
    executable: "{{ pip.executable }}"
    name: pyinterval

- name: Load FPGA module on boot
  copy:
    dest: /etc/modules-load.d/fpga.conf
    content: |
      mlx5_fpga_tools
    mode: 0644

- name: Load FPGA module now
  modprobe: name=mlx5_fpga_tools
  notify: "Restart mst"

- name: Create mst.service systemd dir
  file: dest=/etc/systemd/system/mst.service.d state=directory mode=0755

- name: override mst.service to enable FPGA
  copy:
    dest: /etc/systemd/system/mst.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/etc/init.d/mst start --with_fpga
    mode: 0644
  notify: "Restart mst"
