---
# tasks file for nica
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Downgrade kernel if needed
  include: downgrade-kernel.yml
  when: mlnx_ofed_downgrade_kernel and ansible_distribution == 'CentOS'

- name: Install MLNX OFED
  include_role: name=haggaie.mlnx_ofed

- name: NICA rpm dependencies
  package:
    name:
    - cmake3
    - libuuid-devel
    - python36-pip
    - python36-scapy
    - boost-devel
    - libpcap-devel
  when: ansible_os_family == 'RedHat'

- name: NICA deb dependencies
  package:
    name:
    - cmake
    - uuid-dev
    - python3-pip
    - python3-scapy
    - libboost-all-dev
    - libcap-dev
    state: latest
  when: ansible_os_family == 'Debian'

- name: NICA pip dependencies
  pip:
    executable: "{{ pip.executable }}"
    name: pyinterval
